# Generated by Django 6.0.1 on 2026-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Unique identifier like 'std_sedan'", unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Price (UZS)')),
                ('capacity', models.CharField(help_text="e.g. '3 Guests'", max_length=50)),
                ('rating', models.FloatField(default=5.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cabs/')),
                ('features', models.JSONField(default=list, help_text="List of features e.g. ['AC', 'WiFi']")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
