# Generated by Django 6.0.1 on 2026-01-27 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(default='UZS', max_length=5, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидание'), ('PROCESSING', 'В обработке'), ('PAID', 'Оплачено'), ('FAILED', 'Ошибка'), ('CANCELED', 'Отменено'), ('REFUNDED', 'Возврат')], db_index=True, default='PENDING', max_length=20)),
                ('provider', models.CharField(default='YAGONA', max_length=20, verbose_name='Провайдер')),
                ('external_payment_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID платежа в системе')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx')],
            },
        ),
    ]
