CREATE TABLE `tb_sights` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_vendor` int DEFAULT NULL,
  `category_id` int DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `region_id` int NOT NULL,
  `district_id` int NOT NULL,
  `address` varchar(255) NOT NULL,
  `geolocation` varchar(255) DEFAULT NULL,
  `is_local` int NOT NULL DEFAULT '0',
  `is_foreg` int NOT NULL DEFAULT '0',
  `description` text,
  `sh_description` text,
  `status` enum('new','moderate','active','inactive') DEFAULT 'active',
  `images` text,
  `created_dt` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `allow_from` time DEFAULT NULL,
  `allow_to` time DEFAULT NULL,
  `valid_days` int DEFAULT '30',
  `max_capacity` int DEFAULT NULL,
  `enable_tickets` tinyint(1) DEFAULT '0',
  `opening_times` json DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `extra_services` json DEFAULT NULL,
  `required_conditions` json DEFAULT NULL,
  `policy` text,
  `rate` decimal(6,2) DEFAULT NULL,
  `buy_count` int DEFAULT '0',
  `cancelled_options` enum('refundable','non_refundable') DEFAULT NULL,
