# Generated by Django 6.0.1 on 2026-01-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chatbot', '0002_message_attachment_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('support', 'Support')], max_length=10),
        ),
    ]
