# Generated by Django 5.2.10 on 2026-01-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SightFacility',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название удобства')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'sight facility',
                'verbose_name_plural': 'sight facilities',
                'db_table': 'tb_sight_facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('total_qty', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='общая сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачен')),
                ('is_valid', models.BooleanField(default=True, verbose_name='валиден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tb_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'tb_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('sh_description', models.TextField(blank=True, null=True, verbose_name='короткое описание')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True, verbose_name='геолокация')),
                ('images', models.TextField(blank=True, null=True, verbose_name='изображения (строка через запятую)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20, verbose_name='статус')),
                ('is_foreg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена для иностранцев')),
                ('is_local', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена для местных')),
                ('max_capacity', models.IntegerField(blank=True, null=True, verbose_name='макс. вместимость')),
                ('opening_times', models.JSONField(blank=True, default=dict, null=True, verbose_name='время работы')),
                ('extra_services', models.JSONField(blank=True, default=dict, null=True, verbose_name='доп. услуги')),
                ('required_conditions', models.JSONField(blank=True, default=dict, null=True, verbose_name='требуемые условия')),
                ('enable_tickets', models.BooleanField(default=False, verbose_name='включены билеты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sights', to='hotels.category', verbose_name='категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sights', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'sight',
                'verbose_name_plural': 'sights',
                'db_table': 'tb_sights',
                'ordering': ['-created_at'],
            },
        ),
    ]
