# Generated by Django 5.2.10 on 2026-01-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sights', to='vendors.vendor', verbose_name='вендор'),
        ),
        migrations.AddField(
            model_name='sightfacility',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hotels.sight', verbose_name='достопримечательность'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sight',
            field=models.ForeignKey(db_column='id_sight', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='hotels.sight', verbose_name='достопримечательность'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vendor',
            field=models.ForeignKey(db_column='id_vendor', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='vendors.vendor', verbose_name='вендор'),
        ),
    ]
