# Generated by Django 5.2.10 on 2026-01-14 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='sight',
            options={'ordering': ['-created_at'], 'verbose_name': 'достопримечательность', 'verbose_name_plural': 'достопримечательности'},
        ),
        migrations.AlterModelOptions(
            name='sightfacility',
            options={'ordering': ['name'], 'verbose_name': 'удобство', 'verbose_name_plural': 'удобства'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'билет', 'verbose_name_plural': 'билеты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='enable_tickets',
            field=models.BooleanField(default=False, verbose_name='билеты включены'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='extra_services',
            field=models.JSONField(blank=True, default=dict, verbose_name='доп. услуги'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='images',
            field=models.TextField(blank=True, null=True, verbose_name='изображения (через запятую)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='opening_times',
            field=models.JSONField(blank=True, default=dict, verbose_name='время работы'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='required_conditions',
            field=models.JSONField(blank=True, default=dict, verbose_name='условия'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('pending', 'На модерации')], default='active', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='sightfacility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sightfacility',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='hotels.sight', verbose_name='достопримечательность'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='vendors.vendor', verbose_name='вендор'),
        ),
    ]
