# Generated by Django 5.2.10 on 2026-01-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_category_options_alter_sight_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sights/')),
                ('original_path', models.CharField(help_text='Оригинальный путь из Laravel', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_rel', to='hotels.sight')),
            ],
            options={
                'db_table': 'sight_images',
                'ordering': ['id'],
            },
        ),
    ]
