# Generated by Django 5.2.10 on 2026-01-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_sightimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SightImage',
        ),
    ]
