# Generated by Django 5.2.10 on 2026-01-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_delete_sightimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='enable_tickets',
            field=models.BooleanField(default=False, verbose_name='включены билеты'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='extra_services',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='доп. услуги'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='opening_times',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='время работы'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='required_conditions',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='требуемые условия'),
        ),
    ]
