# Generated by Django 6.0.1 on 2026-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_sight_enable_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='activities',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='развлечения'),
        ),
        migrations.AddField(
            model_name='sight',
            name='amenities_services',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='удобства и услуги'),
        ),
        migrations.AddField(
            model_name='sight',
            name='payment_methods',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='способы оплаты'),
        ),
        migrations.AddField(
            model_name='sight',
            name='safety',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='безопасность'),
        ),
        migrations.AddField(
            model_name='sight',
            name='staff_languages',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='языки персонала'),
        ),
    ]
