# Generated by Django 6.0.1 on 2026-01-22 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_sight_activities_sight_amenities_services_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=255, verbose_name='type_en')),
                ('ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='type_ru')),
                ('uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='type_uz')),
            ],
            options={
                'verbose_name': 'тип комнаты',
                'verbose_name_plural': 'типы комнат',
                'db_table': 'tb_room_types',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
                ('stars', models.IntegerField(default=0, verbose_name='количество звезд')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='рейтинг пользователей')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='депозит (цена)')),
                ('deposit_turizm', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='депозит (туризм)')),
                ('image_id', models.IntegerField(blank=True, null=True, verbose_name='ID главного фото (Legacy)')),
                ('banner_image_id', models.IntegerField(blank=True, null=True, verbose_name='ID баннера (Legacy)')),
                ('gallery', models.TextField(blank=True, null=True, verbose_name='галерея (IDs через запятую)')),
                ('amenities_services', models.JSONField(blank=True, default=dict, null=True, verbose_name='удобства и услуги')),
                ('safety', models.JSONField(blank=True, default=dict, null=True, verbose_name='безопасность')),
                ('payment_methods', models.JSONField(blank=True, default=dict, null=True, verbose_name='способы оплаты')),
                ('staff_languages', models.JSONField(blank=True, default=dict, null=True, verbose_name='языки персонала')),
                ('activities', models.JSONField(blank=True, default=dict, null=True, verbose_name='развлечения')),
                ('services', models.JSONField(blank=True, default=dict, null=True, verbose_name='сервисы')),
                ('hotel_type_id', models.IntegerField(blank=True, null=True, verbose_name='ID типа отеля (Legacy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotels', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='locations.region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'отель',
                'verbose_name_plural': 'отели',
                'db_table': 'tb_hotels_old',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='имя гостя')),
                ('guest_email', models.EmailField(max_length=255, verbose_name='email гостя')),
                ('guest_phone', models.CharField(max_length=50, verbose_name='телефон гостя')),
                ('check_in', models.DateField(verbose_name='заезд')),
                ('check_out', models.DateField(verbose_name='выезд')),
                ('adults', models.IntegerField(default=1, verbose_name='взрослых')),
                ('children', models.IntegerField(default=0, verbose_name='детей')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='общая цена')),
                ('payment_status', models.CharField(default='pending', max_length=50, verbose_name='статус оплаты')),
                ('booking_status', models.CharField(default='pending', max_length=50, verbose_name='статус бронирования')),
                ('selected_rooms_json', models.JSONField(verbose_name='выбранные комнаты (JSON)')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='особые пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotel', verbose_name='отель')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'db_table': 'tb_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircond', models.BooleanField(default=False, verbose_name='кондиционер')),
                ('wifi', models.BooleanField(default=False, verbose_name='wifi')),
                ('tvset', models.BooleanField(default=False, verbose_name='тв')),
                ('freezer', models.BooleanField(default=False, verbose_name='холодильник')),
                ('active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='отель')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.roomtype', verbose_name='тип комнаты')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
                'db_table': 'tb_rooms',
            },
        ),
    ]
