# Generated by Django 6.0.1 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_roomtype_hotel_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (UZ)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание (RU)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='описание (UZ)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (RU)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (UZ)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание (RU)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='описание (UZ)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (RU)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (UZ)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='sh_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='короткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='sh_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='короткое описание (UZ)'),
        ),
    ]
