# Generated by Django 6.0.1 on 2026-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.TextField(blank=True, null=True, verbose_name='изображения (пути через запятую)'),
        ),
    ]
