# Generated by Django 6.0.1 on 2026-01-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='policy',
            field=models.TextField(blank=True, null=True, verbose_name='политика (policy)'),
        ),
    ]
