# Generated by Django 6.0.1 on 2026-01-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_sight_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(verbose_name='дата')),
                ('usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена USD')),
                ('uzs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена UZS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_prices', to='hotels.hotel', verbose_name='отель')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='hotels.roomtype', verbose_name='тип комнаты')),
            ],
            options={
                'verbose_name': 'цена комнаты',
                'verbose_name_plural': 'цены комнат',
                'db_table': 'tb_room_prices',
                'ordering': ['-dt'],
            },
        ),
    ]
