# Generated by Django 6.0.1 on 2026-01-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_roomprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='geolocation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='геолокация'),
        ),
    ]
