# Generated by Django 6.0.1 on 2026-01-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_hotel_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='имя гостя')),
                ('guest_info', models.JSONField(default=dict, verbose_name='информация о госте (JSON)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='сумма')),
                ('hash', models.CharField(max_length=255, unique=True, verbose_name='хэш билета')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=50, verbose_name='статус')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='действителен до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hotels.ticket', verbose_name='билет')),
            ],
            options={
                'verbose_name': 'деталь билета',
                'verbose_name_plural': 'детали билетов',
                'db_table': 'tb_ticket_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
