# Generated by Django 6.0.1 on 2026-01-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_ticketdetail'),
        ('vendors', '0004_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='vendors.vendor', verbose_name='вендор'),
        ),
    ]
