# Generated by Django 6.0.1 on 2026-01-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_extraservice_requiredcondition'),
        ('locations', '0004_delete_sight'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sights', to='locations.district', verbose_name='район'),
        ),
        migrations.AddField(
            model_name='sight',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sights', to='locations.region', verbose_name='регион'),
        ),
    ]
