# Generated by Django 6.0.1 on 2026-01-25 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_sight_district_sight_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='статус бронирования'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmation_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дедлайн подтверждения'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='подтверждено в'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='причина отказа'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='валиден'),
        ),
    ]
