# Generated by Django 6.0.1 on 2026-01-27 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_booking_confirmed_at_booking_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='emehmon_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID в e-mehmon'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='вместимость'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='emehmon_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в e-mehmon'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_room_types', to='hotels.hotel', verbose_name='отель'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price_ref',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='базовая цена (ref)'),
        ),
    ]
