# Generated by Django 6.0.1 on 2026-01-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_add_hotel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcomment',
            name='sight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotels.sight', verbose_name='достопримечательность'),
        ),
        migrations.AlterField(
            model_name='hotelcomment',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hotels.hotel', verbose_name='отель'),
        ),
    ]
