# Generated by Django 6.0.1 on 2026-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_hotelcomment_sight_alter_hotelcomment_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='is_weekend_foreg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена для иностранцев (выходные)'),
        ),
        migrations.AddField(
            model_name='sight',
            name='is_weekend_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена для местных (выходные)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='is_foreg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена для иностранцев (будни)'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='is_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена для местных (будни)'),
        ),
    ]
