# Generated by Django 6.0.1 on 2026-01-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_sight_is_weekend_foreg_sight_is_weekend_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='ticketdetail',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketDetail',
        ),
    ]
