# Generated by Django 6.0.1 on 2026-01-23 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('citizenship', models.CharField(default='Uzbekistan', max_length=100, verbose_name='Гражданство')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='Срок действия паспорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попутчик',
                'verbose_name_plural': 'Попутчики',
                'db_table': 'tb_travelers',
                'ordering': ['-created_at'],
            },
        ),
    ]
