# Generated by Django 6.0.1 on 2026-01-27 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_foreigner',
            field=models.BooleanField(default=False, verbose_name='Иностранец'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
        migrations.CreateModel(
            name='ForeignProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Дата въезда')),
                ('days_remaining', models.IntegerField(default=0, verbose_name='Осталось дней')),
                ('has_violations', models.BooleanField(default=False, verbose_name='Есть нарушения')),
                ('current_registration_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место текущей регистрации')),
                ('visa_expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия визы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_data', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Данные иностранца',
                'verbose_name_plural': 'Данные иностранцев',
                'db_table': 'tb_foreign_profile_data',
            },
        ),
    ]
