# Generated by Django 6.0.1 on 2026-01-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_foreigner_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('vendor_op', 'Vendor Operator'), ('hotel_admin', 'Hotel Admin'), ('moderator', 'Moderator'), ('content_op', 'Content Operator'), ('user', 'User')], db_index=True, default='user', max_length=20),
        ),
    ]
