# Generated by Django 5.2.10 on 2026-01-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('geo', models.CharField(blank=True, max_length=255, null=True, verbose_name='геолокация')),
                ('photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='фото')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
                ('attributes', models.JSONField(blank=True, default=dict, null=True, verbose_name='атрибуты')),
                ('bill_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='платёжные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='hotels.category', verbose_name='категория')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='locations.country', verbose_name='страна')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='locations.district', verbose_name='район')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_vendors', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='locations.region', verbose_name='регион')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='связанный пользователь')),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
                'db_table': 'tb_vendors',
                'ordering': ['-created_at'],
            },
        ),
    ]
