# Generated by Django 6.0.1 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес (RU)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес (UZ)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (RU)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (UZ)'),
        ),
    ]
