# Generated by Django 6.0.1 on 2026-01-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_address_ru_vendor_address_uz_vendor_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=255, null=True)),
                ('model_type', models.CharField(blank=True, max_length=255, null=True)),
                ('model_id', models.BigIntegerField(blank=True, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'медиа файл',
                'verbose_name_plural': 'медиа файлы',
                'db_table': 'media_files',
            },
        ),
    ]
