# Generated by Django 6.0.1 on 2026-01-27 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_module', '__first__'),
        ('vendors', '0004_mediafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена в будни')),
                ('weekend_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена в выходные')),
                ('resident_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена для резидентов')),
                ('non_resident_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена для нерезидентов')),
                ('max_tickets', models.IntegerField(blank=True, null=True, verbose_name='Макс. билетов (null=безлимит)')),
                ('validity_period', models.DurationField(verbose_name='Срок действия билета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип билета',
                'verbose_name_plural': 'Типы билетов',
                'db_table': 'tb_service_tickets',
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='checking_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contacts',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mfo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='МФО'),
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PAID', 'Paid'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_module.currencyrate')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='vendors.serviceticket', verbose_name='Тип билета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Продажа билета',
                'verbose_name_plural': 'Продажи билетов',
                'db_table': 'tb_ticket_sales',
            },
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photos', models.JSONField(blank=True, default=list, null=True, verbose_name='Фотографий')),
                ('schedule', models.JSONField(blank=True, default=dict, null=True, verbose_name='График работы')),
                ('has_tickets', models.BooleanField(default=False, verbose_name='Продажа билетов')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vendors.vendor', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Услуга вендора',
                'verbose_name_plural': 'Услуги вендоров',
                'db_table': 'tb_vendor_services',
            },
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='vendors.vendorservice', verbose_name='Услуга'),
        ),
    ]
