# Generated by Django 6.0.1 on 2026-01-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_serviceticket_vendor_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='operator_role',
            field=models.CharField(choices=[('vendor', 'Vendor Owner'), ('vendor_op', 'Vendor Operator')], default='vendor', max_length=20, verbose_name='Роль оператора'),
        ),
    ]
