# Generated by Django 6.0.1 on 2026-01-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_operator_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='operator_role',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AddField(
            model_name='vendor',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд / Название'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридическое название'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН / Регистрационный номер'),
        ),
        migrations.CreateModel(
            name='VendorUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATOR', 'Operator'), ('ACCOUNTANT', 'Accountant'), ('SUPPORT', 'Support')], default='OWNER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_roles', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Роль пользователя в компании',
                'verbose_name_plural': 'Роли пользователей в компаниях',
                'db_table': 'tb_vendor_user_roles',
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
