# Generated by Django 6.0.1 on 2026-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_vendor_company_name_remove_vendor_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_certs/%Y/%m/%d/', verbose_name='Свидетельство о регистрации (Guvohnoma)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='oked',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ОКЭД'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mfo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='МФО Банка'),
        ),
    ]
