# Generated by Django 6.0.1 on 2026-01-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_bank_name_vendor_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservice',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='rating_rank',
            field=models.IntegerField(default=0),
        ),
    ]
