# Generated by Django 6.0.1 on 2026-01-27 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_module', '0001_initial'),
        ('vendors', '0009_vendorservice_performance_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['user', 'status'], name='tb_ticket_s_user_id_df0794_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['ticket_type', 'status'], name='tb_ticket_s_ticket__bc04e1_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketsale',
            index=models.Index(fields=['purchase_date'], name='tb_ticket_s_purchas_a34125_idx'),
        ),
    ]
