# Generated by Django 6.0.1 on 2026-01-28 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_ticketsale_tb_ticket_s_user_id_df0794_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Кем подтверждено'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Действителен'),
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
    ]
