# Generated by Django 6.0.1 on 2026-01-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_ticketsale_confirmed_at_ticketsale_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='total_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во билетов'),
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='name',
            field=models.CharField(default='Service', max_length=255, verbose_name='Название услуги'),
        ),
    ]
