# Generated by Django 6.0.1 on 2026-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_ticketsale_total_qty_vendorservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsale',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
    ]
