# Generated by Django 6.0.1 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (RU)'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (UZ)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (RU)'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название (UZ)'),
        ),
    ]
