# Generated by Django 6.0.1 on 2026-01-24 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_district_name_ru_district_name_uz_region_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='адрес')),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True, verbose_name='геолокация (lat,lng)')),
                ('price_local', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена (местные)')),
                ('price_foreg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена (иностранцы)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание (UZ)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент (EN/RU)')),
                ('images', models.TextField(blank=True, help_text='Comma separated paths', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sights', to='locations.district', verbose_name='район')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sights', to='locations.region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'достопримечательность',
                'verbose_name_plural': 'достопримечательности',
                'db_table': 'sights',
                'ordering': ['name'],
            },
        ),
    ]
