# Generated by Django 6.0.1 on 2026-01-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_sight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sight',
        ),
    ]
