# Generated by Django 6.0.1 on 2026-01-27 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_module', '0001_initial'),
        ('hotels', '0020_hotel_emehmon_id_roomtype_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Взрослых')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Детей')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CONFIRMED', 'Подтвержден'), ('REJECTED', 'Отклонен'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], default='NEW', max_length=20, verbose_name='Статус')),
                ('emehmon_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в e-mehmon')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='config_module.currencyrate', verbose_name='Валюта')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_bookings', to='hotels.hotel', verbose_name='Отель')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_bookings', to='hotels.roomtype', verbose_name='Тип номера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование (v2)',
                'verbose_name_plural': 'Бронирования (v2)',
                'db_table': 'tb_bookings_v2',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('CONFIRMED', 'Подтвержден'), ('REJECTED', 'Отклонен'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking', verbose_name='Бронирование')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'История статуса бронирования',
                'verbose_name_plural': 'История статусов бронирования',
                'db_table': 'tb_booking_status_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
