# Generated by Django 6.0.1 on 2026-01-27 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('config_module', '0001_initial'),
        ('hotels', '0023_sight_is_weekend_foreg_sight_is_weekend_local_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(db_index=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(db_index=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emehmon_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID в e-mehmon'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('CONFIRMED', 'Подтвержден'), ('REJECTED', 'Отклонен'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], db_index=True, default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='tb_bookings_status_ec3584_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='tb_bookings_check_i_561acd_idx'),
        ),
    ]
