# Generated by Django 6.0.1 on 2026-01-27 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_check_in_alter_booking_check_out_and_more'),
        ('config_module', '0001_initial'),
        ('hotels', '0024_remove_ticket_confirmed_by_remove_ticket_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='tb_bookings_user_id_467cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'status'], name='tb_bookings_hotel_i_b28fa9_idx'),
        ),
    ]
